name: 'Delete Old Images'
description: 'Delete last n images in registry'
author: 'Indiebackend'
inputs:
  scw-token: # change this
    required: true
    description: 'Scaleway Token'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
